/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.*;
import java.util.List;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author user
 */
public class FrmCadUsuario extends javax.swing.JInternalFrame {
     ControllerUsuario ctlUsu = new ControllerUsuario(); 
     ControllerEstado ctlEst = new ControllerEstado();
     ControllerCidade ctlCid = new ControllerCidade();
    /**
     * Creates new form FrmCadUsuario
     */
    public FrmCadUsuario() {
        initComponents();
        jcbCidadeCad.setEnabled(false);
        List<String> siglas = ctlEst.getSiglaEstados();
        while(!siglas.isEmpty())
        {
            jcbEstadoCad.addItem(siglas.get(0));
            siglas.remove(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmailCad = new javax.swing.JTextField();
        txtNomeCad = new javax.swing.JTextField();
        lblEmailCad = new javax.swing.JLabel();
        lblNomeCad = new javax.swing.JLabel();
        lblCidadeCad = new javax.swing.JLabel();
        lblEstadoCad = new javax.swing.JLabel();
        lblSenhaCad = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        jcbEstadoCad = new javax.swing.JComboBox<>();
        jcbCidadeCad = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPasswordCad = new javax.swing.JPasswordField();
        txtPerfilCad = new javax.swing.JTextField();
        lblPerfilCad = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblEmailCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailCad.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailCad.setText("Email:");

        lblNomeCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNomeCad.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCad.setText("Nome:");

        lblCidadeCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCidadeCad.setForeground(new java.awt.Color(255, 255, 255));
        lblCidadeCad.setText("Cidade:");

        lblEstadoCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoCad.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoCad.setText("Estado:");

        lblSenhaCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSenhaCad.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhaCad.setText("Senha:");

        lblCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastro.setText("CADASTRO");

        jcbEstadoCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--" }));
        jcbEstadoCad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbEstadoCadItemStateChanged(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblPerfilCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerfilCad.setForeground(new java.awt.Color(255, 255, 255));
        lblPerfilCad.setText("Perfil:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCidadeCad)
                                .addComponent(lblEstadoCad))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmailCad)
                                    .addComponent(lblNomeCad))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPerfilCad)
                                .addComponent(lblSenhaCad)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailCad, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txtNomeCad, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jcbCidadeCad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbEstadoCad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordCad)
                            .addComponent(txtPerfilCad, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
                .addGap(126, 126, 126))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblCadastro)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailCad)
                    .addComponent(txtEmailCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaCad)
                    .addComponent(jPasswordCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerfilCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerfilCad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoCad)
                    .addComponent(jcbEstadoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeCad)
                    .addComponent(jcbCidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Usuario usuario = new Usuario();
        usuario.setNome(txtNomeCad.getText());
        usuario.setEmail(txtEmailCad.getText());
        usuario.setSenha(String.valueOf(jPasswordCad.getPassword()));
        usuario.setEstado((String) jcbEstadoCad.getSelectedItem());
        usuario.setCidade((String) jcbCidadeCad.getSelectedItem());
       
        
        JOptionPane.showMessageDialog(this,ctlUsu.inserirUsuario(usuario));
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void jcbEstadoCadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbEstadoCadItemStateChanged
      if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
         jcbCidadeCad.setEnabled(true);
         jcbCidadeCad.removeAllItems();
         List<String> cidades=ctlCid.getCidadesByEstados(ctlEst.getIdBySigla(String.valueOf(evt.getItem())));
        
         while(!cidades.isEmpty())
        {
            jcbCidadeCad.addItem(cidades.get(0));
            cidades.remove(0);
        }
        cidades.clear();}
    }//GEN-LAST:event_jcbEstadoCadItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordCad;
    private javax.swing.JComboBox<String> jcbCidadeCad;
    private javax.swing.JComboBox<String> jcbEstadoCad;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCidadeCad;
    private javax.swing.JLabel lblEmailCad;
    private javax.swing.JLabel lblEstadoCad;
    private javax.swing.JLabel lblNomeCad;
    private javax.swing.JLabel lblPerfilCad;
    private javax.swing.JLabel lblSenhaCad;
    private javax.swing.JTextField txtEmailCad;
    private javax.swing.JTextField txtNomeCad;
    private javax.swing.JTextField txtPerfilCad;
    // End of variables declaration//GEN-END:variables
}
